name = "wg-mir-opt"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["oli-obk"]
members = ["oli-obk", "eddyb", "wesleywiser", "vertexclique", "JakobDegen", "dianqk"]
alumni = ["davidtwco", "spastorino"]

[[github]]
orgs = ["rust-lang"]

[website]
name = "MIR optimizations working area"
description = "Writing MIR optimizations and refactoring the MIR to be more optimizable"
repo = "https://forge.rust-lang.org/compiler/working-areas.html"
zulip-stream = "t-compiler/mir-opts"

[permissions]
perf = true
bors.rust.try = true

[[zulip-groups]]
name = "WG-mir-opt"
